<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Vessel</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
        <!-- Place favicon.ico in the root directory -->

		<!-- CSS here -->
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/animate.min.css">
        <link rel="stylesheet" href="css/magnific-popup.css">
        <link rel="stylesheet" href="css/fontawesome-all.min.css">
        <link rel="stylesheet" href="css/odometer.css">
        <link rel="stylesheet" href="css/aos.css">
        <link rel="stylesheet" href="css/owl.carousel.min.css">
        <link rel="stylesheet" href="css/meanmenu.css">
        <link rel="stylesheet" href="css/slick.css">
        <link rel="stylesheet" href="css/default.css">
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="css/responsive.css">
    </head>
    <body>

    <?php
echo '<!-- preloader -->';
echo '<div id="preloader">';
echo '<div id="loading-center">';
echo '<div id="loading-center-absolute">';
echo '<img src="img/icon/preloader.svg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- preloader-end -->';
echo '';
echo '<!-- header-area -->';
echo '<header>';
echo '<div class="header-top-area s-header-top-area d-none d-lg-block">';
echo '<div class="container-fluid s-container-full-padding">';
echo '<div class="row align-items-center">';
echo '<div class="col-lg-6 d-none d-lg-block">';
echo '<div class="header-top-offer">';
echo '<p>Exclusive BLACK FRIDAY offer!</p>';
echo '<span class="coming-time" data-countdown="2022/6/31"></span>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<div class="header-top-right">';
echo '<div class="header-social">';
echo '<ul>';
echo '<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-twitter"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="header-top-action">';
echo '<ul>';
echo '<li>';
echo '<div class="header-top-mail">';
echo '<p><span>|</span><i class="far fa-envelope"></i><a href="mailto:info@gmail.com">tjtimtiman121901@gmail.com</a></p>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="sticky-header" class="transparent-header">';
echo '<div class="container-fluid s-container-full-padding">';
echo '<div class="row">';
echo '<div class="col-12">';
echo '<div class="main-menu menu-style-two">';
echo '<nav>';
echo '<div class="logo">';
echo '<a href="home.php"><img src="img/logo/logo.png" alt="Logo"></a>';
echo '</div>';
echo '<div id="mobile-menu" class="navbar-wrap d-none d-lg-flex">';
echo '<ul>';
echo '<li><a href="home.php">Home</a>';
echo '';
echo '</li>';
echo '<li><a href="#">About</a>';
echo '<ul class="submenu">';
echo '<li><a href="about-us.php">our story</a></li>';
echo '<li><a href="upcoming-games.php">Upcoming Games</a></li>';
echo '';
echo '</ul>';
echo '</li>';
echo '<li><a href="game-overview.php">Overview</a></li>';
echo '<li><a href="community.php">Community</a></li>';
echo '<li><a href="shop.php">Store</a></li>';
echo '<li class="show"><a href="blog.php">Blog</a>';
echo '</li>';
echo '<li><a href="contact.php">contact</a></li>';
echo '<li class="header-shop-cart"><a href="#"><i class="fas fa-user"></i></a>';
echo '<ul class="submenu">';
echo '<li><a href="#">Account Settings</a></li>';
echo '<li><a href="#">Orders History</a></li>';
echo '<li><a href="#">Activity</a></li>';
echo '<li><a href="#">Notification</a></li>';
echo '<li><a href="#">Messages</a></li>';
echo '<li><a href="index.php">Logout</a></li>';
echo '</ul>';
echo '</ul>';
echo '</div>';
echo '<div class="header-action">';
echo '<ul>';
echo '<li class="header-shop-cart"><a href="#"><i class="fas fa-shopping-basket"></i><span>0</span></a>';
echo '<ul class="minicart">';
echo '<li class="d-flex align-items-start">';
echo '<div class="cart-img">';
echo '<a href="#">';
echo '<img src="img/product/cart_p01.jpg" alt="">';
echo '</a>';
echo '</div>';
echo '<div class="cart-content">';
echo '<h4>';
echo '<a href="#">ASUS ROG ZEPHYRUS G14 22</a>';
echo '</h4>';
echo '<div class="cart-price">';
echo '<span class="new">₱89,000.00</span>';
echo '<span>';
echo '<del>₱89,000.00</del>';
echo '</span>';
echo '</div>';
echo '</div>';
echo '<div class="del-icon">';
echo '<a href="#">';
echo '<i class="far fa-trash-alt"></i>';
echo '</a>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="total-price">';
echo '<span class="f-left">Total:</span>';
echo '<span class="f-right">₱90,000.00</span>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="checkout-link">';
echo '<a href="#">Shopping Cart</a>';
echo '<a class="red-color" href="#">Checkout</a>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</li>';
echo '<li class="header-search"><a href="#" data-toggle="modal" data-target="#search-modal"><i class="fas fa-search"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '</div>';
echo '<div class="mobile-menu"></div>';
echo '</div>';
echo '<!-- Modal Search -->';
echo '<div class="modal fade" id="search-modal" tabindex="-1" role="dialog" aria-hidden="true">';
echo '<div class="modal-dialog" role="document">';
echo '<div class="modal-content">';
echo '<form>';
echo '<input type="text" placeholder="Search here...">';
echo '<button><i class="fa fa-search"></i></button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<!-- header-area-end -->';
echo '';
echo '<!-- main-area -->';
echo '<main>';
echo '';
echo '<!-- breadcrumb-area -->';
echo '<section class="breadcrumb-area breadcrumb-bg third-breadcrumb-bg">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-12">';
echo '<div class="breadcrumb-content text-center">';
echo '<h2>Blog <span>Details</span></h2>';
echo '<nav aria-label="breadcrumb">';
echo '<ol class="breadcrumb">';
echo '<li class="breadcrumb-item"><a href="home.php">Home</a></li>';
echo '<li class="breadcrumb-item active" aria-current="page">Blog Details</li>';
echo '</ol>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- breadcrumb-area-end -->';
echo '';
echo '<!-- blog-area -->';
echo '<section class="blog-area primary-bg pt-120 pb-175">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8">';
echo '<div class="blog-list-post blog-details-wrap">';
echo '<div class="blog-list-post-content">';
echo '<div class="blog-list-post-tag mb-25">';
echo '<a href="#">shooting</a>';
echo '</div>';
echo '<h2>V RISING HITS 1 MILLION PLAYERS AFTER JUST A WEEK</h2>';
echo '<div class="blog-meta">';
echo '<ul>';
echo '<li>bY <a href="#">AUSTIN WOOD</a> PUBLISHED ABOUT 8 HOURS AGO</li>';
echo '</ul>';
echo '</div>';
echo '<p>V Rising has hit one million players exactly one week after its Steam launch.</p>';
echo '<h4>V RISING QUICKLY!</h4>';
echo '<p>V Rising quickly rocketed to';
echo 'the top of Steams best-seller list and went on to sell 500,000';
echo 'copies in just three days. That pace has barely changed, with';
echo 'developer Stunlock Studios, previously best known for Battlerite,';
echo 'selling another 500,000 copies in the four days since.</p>';
echo '<p style="text-align: justify"> The games';
echo 'official Twitter account confirmed the milestone earlier today.';
echo '"1,000,000 Vampires have risen from their slumber," the announcement reads.';
echo '"Thank you all for being part of this achievement!"</p>';
echo '<div class="row">';
echo '<div class="col-sm-6">';
echo '<div class="blog-details-img">';
echo '<img src="img/blog/blog_details_img01.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-6">';
echo '<div class="blog-details-img">';
echo '<img src="img/blog/blog_details_img02.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<p style="text-align: justify">V Risings explosive launch has slowed slightly in the';
echo 'past few days, but only in the way that a rocket might';
echo 'technically slow down as it punches through layers of our atmosphere.';
echo 'According to Steam Charts, its 24-hour player peak is 135,042, putting';
echo 'it firmly in the storefronts most-played games and only slightly behind';
echo 'its all-time peak of 150,645. </p>';
echo '<blockquote>';
echo '“ It sold 500,000 copies in its first three days”';
echo '</blockquote>';
echo '<p style="text-align: justify">At the time of writing, V Rising is sitting at 124,572';
echo 'concurrent players, putting it at Steams number seven right';
echo 'behind Destiny 2, which is currently celebrating the launch of';
echo 'the Season of the Haunted and the release of Solar 3.0';
echo 'both big draws for whats already one of Steams biggest games</p>';
echo '<ul class="blog-details-list">';
echo '<li>Sapien auctor tortoris vulputate sapien ?</li>';
echo '<li>Curabitr lacus vitae tellus lacinia pretium vulputate ?</li>';
echo '<li>Tellus orci auctor augue mauris ?</li>';
echo '</ul>';
echo '<p>Sapien auctor tortoris vulputate sapien tortor velit. Sed nul congue euqua molestie grvida ipsums Curabitr lacus vitae';
echo 'tellus lacinia pretium. Proin vestibulum sollcitudin tortor, quis auctor rutru.Nisl nisi scelerisque eu ultrices vitae.';
echo 'Eu lobortis elementum nibh tellus molestie.</p>';
echo '<div class="blog-list-post-bottom">';
echo '<ul>';
echo '<li>';
echo '<i class="fas fa-tag"></i>';
echo '<span>tags :</span>';
echo '<a href="#">dota2</a>';
echo '<a href="#">esports</a>';
echo '<a href="#">matches</a>';
echo '</li>';
echo '<li>';
echo '<span>SHARE :</span>';
echo '<div class="blog-post-share">';
echo '<a href="#"><i class="fab fa-facebook-f"></i></a>';
echo '<a href="#"><i class="fab fa-twitter"></i></a>';
echo '<a href="#"><i class="fab fa-pinterest-p"></i></a>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="blog-comment mb-75">';
echo '<div class="sidebar-widget-title blog-details-title mb-35">';
echo '<h4>COMMENTS <span>(12)</span></h4>';
echo '</div>';
echo '<ul>';
echo '<li>';
echo '<div class="comment-avatar-thumb">';
echo '<img src="img/blog/comment_thumb01.jpg" alt="">';
echo '</div>';
echo '<div class="comment-text">';
echo '<div class="comment-avatar-info">';
echo '<h4><a href="#">alexander hartmann</a><span class="comment-time">10 May 2022, 7:06 am</span></h4>';
echo '<div class="comment-reply">';
echo '<a href="#"><i class="fas fa-reply"></i></a>';
echo '</div>';
echo '</div>';
echo '<p>Sapien auctor tortoris vulputate sapien tortor Sed nul congue euqua molestie grvida ipsums Curabitr lacus vitae tellus';
echo 'lacinia pretium.</p>';
echo '</div>';
echo '</li>';
echo '<li class="comment-children">';
echo '<div class="comment-avatar-thumb">';
echo '<img src="img/blog/comment_thumb02.jpg" alt="">';
echo '</div>';
echo '<div class="comment-text">';
echo '<div class="comment-avatar-info">';
echo '<h4><a href="#">aretha wilson</a><span class="comment-time">10 May 2022, 9:32 am</span></h4>';
echo '<div class="comment-reply">';
echo '<a href="#"><i class="fas fa-reply"></i></a>';
echo '</div>';
echo '</div>';
echo '<p>Sapien auctor tortoris vulputate sapien tortor Sed nul congue grvida ipsums Curabitr lacus vitae tellus';
echo 'lacinia pretium.</p>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div class="comment-reply-box">';
echo '<div class="sidebar-widget-title blog-details-title mb-35">';
echo '<h4>LEAVE A <span>COMMENT</span></h4>';
echo '</div>';
echo '<form action="#" class="comment-form">';
echo '<textarea name="message" id="comment-message" placeholder="Your Comment"></textarea>';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '<input type="text" placeholder="Your Name*">';
echo '</div>';
echo '<div class="col-md-6">';
echo '<input type="email" placeholder="Your Email*">';
echo '</div>';
echo '</div>';
echo '<div class="comment-check-box mb-25">';
echo '<input type="checkbox" id="comment-check">';
echo '<label for="comment-check">Save my name and email in this browser for the next time I comment.</label>';
echo '</div>';
echo '<button class="btn btn-style-two">Submit</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<aside class="blog-sidebar">';
echo '<div class="widget mb-45">';
echo '<div class="sidebar-about">';
echo '<div class="sidebar-about-thumb">';
echo '<img src="img/blog/sidebar_about_thumb.jpg" alt="">';
echo '</div>';
echo '<div class="sidebar-widget-title mb-15">';
echo '<h4>ABOUT THE <span>AUTHOR</span></h4>';
echo '</div>';
echo '<div class="sidebar-about-content">';
echo '<p style="text-align: justify">Our team will sometimes take';
echo 'trips and other hospitality to attend shows';
echo 'or see products. That does not';
echo 'affect how we think or write about those products or games,';
echo 'but it does affect whether we can cover certain products or events,';
echo 'particularly when otherwise we would not have had that coverage opportunity.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="widget mb-45">';
echo '<div class="sidebar-search">';
echo '<form action="#">';
echo '<input type="text" placeholder="Type and hit enter...">';
echo '<button><i class="fas fa-search"></i></button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '<div class="widget mb-45">';
echo '<div class="sidebar-widget-title mb-25">';
echo '<h4>category <span>post</span></h4>';
echo '</div>';
echo '<div class="sidebar-cat">';
echo '<ul>';
echo '<li><a href="#">Released Games ( 12 )</a></li>';
echo '<li><a href="#">Trending ( 103 )</a></li>';
echo '<li><a href="#">Valorant ( 25 )</a></li>';
echo '<li><a href="#">Adventure ( 17 )</a></li>';
echo '<li><a href="#">Upcoming ( 42 )</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="widget mb-45">';
echo '<div class="sidebar-widget-title mb-25">';
echo '<h4>Recent <span>post</span></h4>';
echo '</div>';
echo '<div class="rc-post-list">';
echo '<ul>';
echo '<li>';
echo '<div class="rc-post-thumb">';
echo '<a href="#"><img src="img/blog/rc_post_thumb01.jpg" alt=""></a>';
echo '</div>';
echo '<div class="rc-post-content">';
echo '<h5><a href="#">EVERYONE zombie</a></h5>';
echo '<span>MAY 25, 2022</span>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="rc-post-thumb">';
echo '<a href="#"><img src="img/blog/rc_post_thumb02.jpg" alt=""></a>';
echo '</div>';
echo '<div class="rc-post-content">';
echo '<h5><a href="#">Archery World Tour</a></h5>';
echo '<span>MAY 25, 2022</span>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="rc-post-thumb">';
echo '<a href="#"><img src="img/blog/rc_post_thumb03.jpg" alt=""></a>';
echo '</div>';
echo '<div class="rc-post-content">';
echo '<h5><a href="#">The Ranger Magic</a></h5>';
echo '<span>MAY 25, 2022</span>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="widget mb-45">';
echo '<div class="sidebar-widget-title mb-25">';
echo '<h4>TRENDING <span>MATCHES</span></h4>';
echo '</div>';
echo '<div class="sidebar-trending-match">';
echo '<ul>';
echo '<li>';
echo '<div class="sidebar-trend-match-thumb">';
echo '<a href="#"><img src="img/blog/trend_match_thumb01.png" alt=""></a>';
echo '</div>';
echo '<div class="sidebar-trend-match-action">';
echo '<span>0</span> <span>-</span> <span>3</span>';
echo '</div>';
echo '<div class="sidebar-trend-match-thumb">';
echo '<a href="#"><img src="img/blog/trend_match_thumb02.png" alt=""></a>';
echo '</div>';
echo '<div class="sidebar-trend-match-date">';
echo '<span>MAY 25, 2022</span>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="sidebar-trend-match-thumb">';
echo '<a href="#"><img src="img/blog/trend_match_thumb03.png" alt=""></a>';
echo '</div>';
echo '<div class="sidebar-trend-match-action">';
echo '<span>0</span> <span>-</span> <span>7</span>';
echo '</div>';
echo '<div class="sidebar-trend-match-thumb">';
echo '<a href="#"><img src="img/blog/trend_match_thumb04.png" alt=""></a>';
echo '</div>';
echo '<div class="sidebar-trend-match-date">';
echo '<span>MAY 25, 2022</span>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="sidebar-trend-match-thumb">';
echo '<a href="#"><img src="img/blog/trend_match_thumb05.png" alt=""></a>';
echo '</div>';
echo '<div class="sidebar-trend-match-action">';
echo '<span>0</span> <span>-</span> <span>3</span>';
echo '</div>';
echo '<div class="sidebar-trend-match-thumb">';
echo '<a href="#"><img src="img/blog/trend_match_thumb06.png" alt=""></a>';
echo '</div>';
echo '<div class="sidebar-trend-match-date">';
echo '<span>MAY 25, 2022</span>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="widget">';
echo '<div class="sidebar-widget-title mb-25">';
echo '<h4>TAGS <span>post</span></h4>';
echo '</div>';
echo '<div class="sidebar-tag-list">';
echo '<ul>';
echo '<li><a href="#">pubg</a></li>';
echo '<li><a href="#">dota 2</a></li>';
echo '<li><a href="#">zombie</a></li>';
echo '<li><a href="#">call of duty</a></li>';
echo '<li><a href="#">development</a></li>';
echo '<li><a href="#">zombieland 2</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</aside>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- blog-area-end -->';
echo '';
echo '</main>';
echo '<!-- main-area-end -->';
echo '';
echo '<!-- footer-area -->';
echo '<footer>';
echo '<div class="footer-top footer-bg s-footer-bg">';
echo '<!-- newsletter-area -->';
echo '<div class="newsletter-area s-newsletter-area">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-12">';
echo '<div class="newsletter-wrap">';
echo '<div class="section-title newsletter-title">';
echo '<h2>Our <span>Newsletter</span></h2>';
echo '</div>';
echo '<div class="newsletter-form">';
echo '<form action="#">';
echo '<div class="newsletter-form-grp">';
echo '<i class="far fa-envelope"></i>';
echo '<input type="email" placeholder="Enter your email...">';
echo '</div>';
echo '<button>SUBSCRIBE <i class="fas fa-paper-plane"></i></button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- newsletter-area-end -->';
echo '<div class="container">';
echo '<div class="row justify-content-between">';
echo '<div class="col-xl-3 col-lg-4 col-md-6">';
echo '<div class="footer-widget mb-50">';
echo '<div class="footer-logo mb-35">';
echo '<a href="index.html"><img src="img/logo/logo.png" alt=""></a>';
echo '</div>';
echo '<div class="footer-text">';
echo '<p>Gemas marketplace the relase etras thats sheets continig passag.</p>';
echo '<div class="footer-contact">';
echo '<ul>';
echo '<li><i class="fas fa-map-marker-alt"></i> <span>Address : </span>Bangbangalon, Boac, Marinduque</li>';
echo '<li><i class="fas fa-headphones"></i> <span>Phone : </span>+24 1245 654 235</li>';
echo '<li><i class="fas fa-envelope-open"></i><span>Email : </span>tjtimtiman121901@gmail.com</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-2 col-lg-3 col-sm-6">';
echo '<div class="footer-widget mb-50">';
echo '<div class="fw-title mb-35">';
echo '<h5>Links</h5>';
echo '</div>';
echo '<div class="fw-link">';
echo '<ul>';
echo '<li><a href="home.php">Home</a></li>';
echo '<li><a href="about-us.php">Our Story</a></li>';
echo '<li><a href="game-overview.php">Overview</a></li>';
echo '<li><a href="community.php">Community</a></li>';
echo '<li><a href="shop.php">Store</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-2 col-lg-3 col-sm-6">';
echo '<div class="footer-widget mb-50">';
echo '<div class="fw-title mb-35">';
echo '<h5>Need Help?</h5>';
echo '</div>';
echo '<div class="fw-link">';
echo '<ul>';
echo '<li><a href="#">Terms & Conditions</a></li>';
echo '<li><a href="#">Privacy Policy</a></li>';
echo '<li><a href="#">Refund Policy</a></li>';
echo '<li><a href="#">Affiliate</a></li>';
echo '<li><a href="#">FAQ</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-3 col-lg-4 col-md-6">';
echo '<div class="footer-widget mb-50">';
echo '<div class="fw-title mb-35">';
echo '<h5>Follow us</h5>';
echo '</div>';
echo '<div class="footer-social">';
echo '<ul>';
echo '<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-twitter"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="footer-widget mb-50">';
echo '<div class="fw-title mb-35">';
echo '<h5>Newsletter Sign Up</h5>';
echo '</div>';
echo '<div class="footer-newsletter">';
echo '<form action="#">';
echo '<input type="text" placeholder="Enter your email">';
echo '<button><i class="fas fa-rocket"></i></button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="footer-fire"><img src="img/images/sword_fire.png" alt=""></div>';
echo '<div class="footer-fire footer-fire-right"><img src="img/images/sword_ice.png" alt=""></div>';
echo '</div>';
echo '<div class="copyright-wrap s-copyright-wrap">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 col-md-6">';
echo '<div class="copyright-text">';
echo '<p>Copyright © 2022 <a href="#">Vessel</a> All Rights Reserved.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 col-md-6 d-none d-md-block">';
echo '<div class="payment-method-img text-right">';
echo '<img src="img/images/card_img.png" alt="img">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '<!-- footer-area-end -->';
echo '';
?>




		<!-- JS here -->
        <script src="js/vendor/jquery-3.4.1.min.js"></script>
        <script src="js/popper.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/isotope.pkgd.min.js"></script>
        <script src="js/slick.min.js"></script>
        <script src="js/jquery.meanmenu.min.js"></script>
        <script src="js/wow.min.js"></script>
        <script src="js/aos.js"></script>
        <script src="js/jquery.lettering.js"></script>
        <script src="js/jquery.textillate.js"></script>
        <script src="js/jquery.odometer.min.js"></script>
        <script src="js/jquery.appear.js"></script>
        <script src="js/owl.carousel.min.js"></script>
        <script src="js/jquery.countdown.min.js"></script>
        <script src="js/jquery.scrollUp.min.js"></script>
        <script src="js/imagesloaded.pkgd.min.js"></script>
        <script src="js/jquery.magnific-popup.min.js"></script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>
