<!doctype html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Vessel</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
        <!-- Place favicon.ico in the root directory -->

		<!-- CSS here -->
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/animate.min.css">
        <link rel="stylesheet" href="css/magnific-popup.css">
        <link rel="stylesheet" href="css/fontawesome-all.min.css">
        <link rel="stylesheet" href="css/odometer.css">
        <link rel="stylesheet" href="css/aos.css">
        <link rel="stylesheet" href="css/owl.carousel.min.css">
        <link rel="stylesheet" href="css/meanmenu.css">
        <link rel="stylesheet" href="css/slick.css">
        <link rel="stylesheet" href="css/default.css">
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="css/responsive.css">


    </head>
    <?php
echo '<body>';
echo '';
echo '<!-- preloader -->';
echo '<div id="preloader">';
echo '<div id="loading-center">';
echo '<div id="loading-center-absolute">';
echo '<img src="img/icon/preloader.svg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- preloader-end -->';
echo '';
echo '<!-- header-area -->';
echo '<header>';
echo '<div class="header-top-area s-header-top-area d-none d-lg-block">';
echo '<div class="container-fluid s-container-full-padding">';
echo '<div class="row align-items-center">';
echo '<div class="col-lg-6 d-none d-lg-block">';
echo '<div class="header-top-offer">';
echo '<p>Exclusive BLACK FRIDAY offer!</p>';
echo '<span class="coming-time" data-countdown="2022/6/31"></span>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<div class="header-top-right">';
echo '<div class="header-social">';
echo '<ul>';
echo '<!-- BUTTON -->';
echo '<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-twitter"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="header-top-action">';
echo '<ul>';
echo '<li>';
echo '<div class="header-top-mail">';
echo '<p><span>|</span><i class="far fa-envelope"></i><a href="mailto:info@gmail.com">tjtimtiman121901@gmail.com</a></p>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="sticky-header" class="transparent-header">';
echo '<div class="container-fluid s-container-full-padding">';
echo '<div class="row">';
echo '<div class="col-12">';
echo '<div class="main-menu menu-style-two">';
echo '<nav>';
echo '<div class="logo">';
echo '<a href="home.php"><img src="img/logo/logo.png" alt="Logo"></a>';
echo '</div>';
echo '<div id="mobile-menu" class="navbar-wrap d-none d-lg-flex">';
echo '<ul>';
echo '<li class="show"><a href="home.php">Home</a>';
echo '</li>';
echo '<li><a href="#">About</a>';
echo '<ul class="submenu">';
echo '<li><a href="about-us.php">our story</a></li>';
echo '<li><a href="upcoming-games.php">Upcoming Games</a></li>';
echo '</ul>';
echo '</li>';
echo '<li><a href="game-overview.php">Overview</a></li>';
echo '<li><a href="community.php">Community</a></li>';
echo '<li><a href="shop.php">Store</a></li>';
echo '<li><a href="blog.php">Blog</a>';
echo '</li>';
echo '<li><a href="contact.php">contact</a></li>';
echo '<li class="header-shop-cart"><a href="#"><i class="fas fa-user"></i></a>';
echo '<ul class="submenu">';
echo '<li><a href="#">Account Settings</a></li>';
echo '<li><a href="#">Orders History</a></li>';
echo '<li><a href="#">Activity</a></li>';
echo '<li><a href="#">Notification</a></li>';
echo '<li><a href="#">Messages</a></li>';
echo '<li><a href="index.php">Logout</a></li>';
echo '</ul>';
echo '</div>';
echo '';
echo '<div class="header-action">';
echo '<ul>';
echo '';
echo '<li class="header-shop-cart"><a href="#"><i class="fas fa-shopping-basket"></i><span>0</span></a>';
echo '<ul class="minicart">';
echo '<li class="d-flex align-items-start">';
echo '<div class="cart-img">';
echo '<a href="#">';
echo '<img src="img/product/cart_p01.jpg" alt="">';
echo '</a>';
echo '</div>';
echo '<div class="cart-content">';
echo '<h4>';
echo '<a href="#">ASUS ROG ZEPHYRUS G14 22</a>';
echo '</h4>';
echo '<div class="cart-price">';
echo '<span class="new">₱89,000.00</span>';
echo '<span>';
echo '<del>₱89,000.00</del>';
echo '</span>';
echo '</div>';
echo '</div>';
echo '<div class="del-icon">';
echo '<a href="#">';
echo '<i class="far fa-trash-alt"></i>';
echo '</a>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="total-price">';
echo '<span class="f-left">Total:</span>';
echo '<span class="f-right">₱90,000.00</span>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="checkout-link">';
echo '<a href="#">Shopping Cart</a>';
echo '<a class="red-color" href="#">Checkout</a>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</li>';
echo '<li class="header-search"><a href="#" data-toggle="modal" data-target="#search-modal"><i class="fas fa-search"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '</div>';
echo '<div class="mobile-menu"></div>';
echo '</div>';
echo '<!-- Modal Search -->';
echo '<div class="modal fade" id="search-modal" tabindex="-1" role="dialog" aria-hidden="true">';
echo '<div class="modal-dialog" role="document">';
echo '<div class="modal-content">';
echo '<form>';
echo '<input type="text" placeholder="Search here...">';
echo '<button><i class="fa fa-search"></i></button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<!-- header-area-end -->';
echo '';
echo '<!-- main-area -->';
echo '<main>';
echo '';
echo '<!-- slider-area -->';
echo '<section class="slider-area">';
echo '<div class="slider-active">';
echo '<div class="single-slider slider-bg slider-style-two">';
echo '<div class="container-fluid container-full-padding">';
echo '<div class="row">';
echo '<div class="col-xl-6 col-lg-7 col-md-11">';
echo '<div class="slider-content">';
echo '<h6 data-animation="fadeInUp" data-delay=".4s">Gaming world</h6>';
echo '<h2 data-animation="fadeInUp" data-delay=".4s">Daily <span>Gaming</span> Updates</h2>';
echo '<p data-animation="fadeInUp" data-delay=".6s">The Vessel gaming section brings the latest video game news, reviews of the most exciting releases, and interviews with the industry’s biggest names.';
echo '</p>';
echo '<a href="#" class="btn btn-style-two" data-animation="fadeInUp" data-delay=".8s">READ MORE</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="slider-img" data-animation="slideInRightS" data-delay=".6s"><img src="img/slider/slider_img01.png" alt=""></div>';
echo '<div class="slider-img slider-img2" data-animation="slideInLeftS" data-delay=".6s"><img src="img/slider/slider_img02.png" alt=""></div>';
echo '<div class="slider-circle-shape"><img src="img/slider/slider_circle.png" alt="" class="rotateme"></div>';
echo '</div>';
echo '<div class="single-slider slider-bg slider-style-two" style="background-image: url(img/slider/slider_bg.jpg);">';
echo '<div class="container-fluid container-full-padding">';
echo '<div class="row">';
echo '<div class="col-xl-6 col-lg-7 col-md-11">';
echo '<div class="slider-content">';
echo '<h6 data-animation="fadeInUp" data-delay=".4s">TOP GAMES</h6>';
echo '<h2 data-animation="fadeInUp" data-delay=".4s">Valorant <span>Riot</span> Games</h2>';
echo '<p data-animation="fadeInUp" data-delay=".6s">A free-to-play 5v5 character-based tactical shooter and objective-based game, developed and published by Riot Games,</p>';
echo '<a href="#" class="btn btn-style-two" data-animation="fadeInUp" data-delay=".8s">READ MORE</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="slider-img" data-animation="slideInRightS" data-delay=".6s"><img src="img/slider/slider_img01.png" alt=""></div>';
echo '<div class="slider-img slider-img2" data-animation="slideInLeftS" data-delay=".6s"><img src="img/slider/slider_img02.png" alt=""></div>';
echo '<div class="slider-circle-shape"><img src="img/slider/slider_circle.png" alt="" class="rotateme"></div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- slider-area-end -->';
echo '';
echo '<!-- new-games-area -->';
echo '<section class="released-games-area gray-bg pt-115 pb-70">';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-xl-6 col-lg-8">';
echo '<div class="section-title title-style-three text-center mb-20">';
echo '<h2>TRENDING <span>GAMES</span></h2>';
echo '<p>Here are the hottest games and reviews that will not waste your time with unrelated nonsense.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row align-items-center">';
echo '<div class="col-xl-8 col-lg-12">';
echo '<div class="released-game-active">';
echo '<div class="released-game-carousel">';
echo '<div class="released-game-item">';
echo '<div class="released-game-item-bg"></div>';
echo '<div class="released-game-img">';
echo '<img src="img/images/released_game_img01.jpg" alt="">';
echo '</div>';
echo '<div class="released-game-content">';
echo '<div class="released-game-rating">';
echo '<h5>Rating :</h5>';
echo '<div class="released-rating">';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '</div>';
echo '</div>';
echo '<h4>Valo<span>rant</span></h4>';
echo '<div class="released-game-list mb-15">';
echo '<ul>';
echo '<li><span>Genre :</span>First Person Shooter</li>';
echo '<li><span>Developer :</span>Riot Games</li>';
echo '<li><span>Platform :</span>PC</li>';
echo '</ul>';
echo '</div>';
echo '<p>Compete with other 5 players where one team attacks and the other defends. Search and Destroy.</p>';
echo '<a href="game-single.php" class="btn btn-style-two">play Now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="released-game-carousel">';
echo '<div class="released-game-item">';
echo '<div class="released-game-item-bg"></div>';
echo '<div class="released-game-img">';
echo '<img src="img/images/released_game_img02.jpg" alt="">';
echo '</div>';
echo '<div class="released-game-content">';
echo '<div class="released-game-rating">';
echo '<h5>Rating :</h5>';
echo '<div class="released-rating">';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '</div>';
echo '</div>';
echo '<h4>Mine<span>craft</span></h4>';
echo '<div class="released-game-list mb-15">';
echo '<ul>';
echo '<li><span>Genre :</span>Simulation, Sandbox</li>';
echo '<li><span>Developer :</span>Mojang Studios</li>';
echo '<li><span>Platform :</span>PC, Console, Mobile Devices</li>';
echo '</ul>';
echo '</div>';
echo '<p>Explore infinite worlds, create, explore and survive alone or with friends</p>';
echo '<a href="game-single2.php" class="btn btn-style-two">buy now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="released-game-carousel">';
echo '<div class="released-game-item">';
echo '<div class="released-game-item-bg"></div>';
echo '<div class="released-game-img">';
echo '<img src="img/images/released_game_img03.jpg" alt="">';
echo '</div>';
echo '<div class="released-game-content">';
echo '<div class="released-game-rating">';
echo '<h5>Rating :</h5>';
echo '<div class="released-rating">';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '</div>';
echo '</div>';
echo '<h4>GhostWire <span>Tokyo</span></h4>';
echo '<div class="released-game-list mb-15">';
echo '<ul>';
echo '<li><span>Genre :</span>Action, Adventure, RPG</li>';
echo '<li><span>Developer :</span>Bethesda</li>';
echo '<li><span>Platform :</span>PC, COnsole</li>';
echo '</ul>';
echo '</div>';
echo '<p>Master a powerful arsenal of abilities to unravel the dark truth as you FACE THE UNKNOWN in Ghostwire: Tokyo.</p>';
echo '<a href="game-single2.php" class="btn btn-style-two">buy now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="released-game-carousel">';
echo '<div class="released-game-item">';
echo '<div class="released-game-item-bg"></div>';
echo '<div class="released-game-img">';
echo '<img src="img/images/released_game_img04.jpg" alt="">';
echo '</div>';
echo '<div class="released-game-content">';
echo '<div class="released-game-rating">';
echo '<h5>Rating :</h5>';
echo '<div class="released-rating">';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '</div>';
echo '</div>';
echo '<h4>Dying<span>Light 2</span></h4>';
echo '<div class="released-game-list mb-15">';
echo '<ul>';
echo '<li><span>Genre :</span>Action, Adventure, RPG</li>';
echo '<li><span>Developer :</span>Techland</li>';
echo '<li><span>Platform :</span>PC, Console</li>';
echo '</ul>';
echo '</div>';
echo '<p>Use your agility and combat skills to survive, and reshape the world. Your choices matter</p>';
echo '<a href="game-single2.php" class="btn btn-style-two">buy now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-4 col-lg-12">';
echo '<div class="released-game-nav">';
echo '<div class="released-game-nav-item">';
echo '<img src="img/images/release_game_nav01.jpg" alt="">';
echo '</div>';
echo '<div class="released-game-nav-item">';
echo '<img src="img/images/release_game_nav02.jpg" alt="">';
echo '</div>';
echo '<div class="released-game-nav-item">';
echo '<img src="img/images/release_game_nav03.jpg" alt="">';
echo '</div>';
echo '<div class="released-game-nav-item">';
echo '<img src="img/images/release_game_nav04.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- new-games-area-end -->';
echo '';
echo '<!-- gamers-area -->';
echo '<section class="just-gamers-area just-gamers-bg pt-115 pb-120">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-xl-5 col-lg-6 col-md-10">';
echo '<div class="section-title title-style-three white-title mb-70">';
echo '<h2>JUST FOR <span>GAMERS</span></h2>';
echo '<p>Wield a combination of upgradeable elemental powers and';
echo 'ghost-hunting skills to combat the supernatural threat.</p>';
echo '</div>';
echo '<div class="just-gamers-list">';
echo '<ul>';
echo '<li>';
echo '<div class="just-gamers-list-icon">';
echo '<img src="img/icon/gamer_list_icon01.png" alt="">';
echo '</div>';
echo '<div class="just-gamers-list-content fix">';
echo '<h5>About this Game</h5>';
echo '<p>Explore a unique vision of Tokyo twisted by a supernatural presence.</p>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="just-gamers-list-icon">';
echo '<img src="img/icon/gamer_list_icon02.png" alt="">';
echo '</div>';
echo '<div class="just-gamers-list-content fix">';
echo '<h5>Design & Strategy</h5>';
echo '<p>Explore a unique vision of Tokyo twisted by a supernatural presence. </p>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="just-gamers-list-icon">';
echo '<img src="img/icon/gamer_list_icon03.png" alt="">';
echo '</div>';
echo '<div class="just-gamers-list-content fix">';
echo '<h5>Objectives</h5>';
echo '<p>Explore a unique vision of Tokyo twisted by a supernatural presence.</p>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-7 col-lg-6 d-none d-lg-block">';
echo '<div class="just-gamers-img">';
echo '<img src="img/images/just_gamers_img.png" alt="" class="just-gamers-character">';
echo '<div class="just-gamers-circle-shape">';
echo '<img src="img/images/gamers_circle_line.png" alt="">';
echo '<img src="img/images/gamers_circle_shape.png" alt="" class="rotateme">';
echo '</div>';
echo '<img src="img/images/just_gamers_chart.png" alt="" class="gamers-chart-shape">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- gamers-area-end -->';
echo '';
echo '<!-- featured-game-area -->';
echo '<section class="featured-game-area position-relative pt-115 pb-90">';
echo '<div class="featured-game-bg"></div>';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-xl-6 col-lg-8">';
echo '<div class="section-title title-style-three text-center mb-70">';
echo '<h2>FEATURED <span>GAMES</span></h2>';
echo '<p>Here are the featured games and reviews that will not waste your time with unrelated nonsense.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row featured-active">';
echo '<div class="col-lg-4 col-sm-6 grid-item">';
echo '<div class="featured-game-item mb-30">';
echo '<div class="featured-game-thumb">';
echo '<img src="img/images/featured_game_thumb01.jpg" alt="">';
echo '</div>';
echo '<div class="featured-game-content">';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '<div class="featured-game-content featured-game-overlay-content">';
echo '<div class="featured-game-icon"><img src="img/icon/featured_game_icon.png" alt=""></div>';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-6 grid-item">';
echo '<div class="featured-game-item mb-30">';
echo '<div class="featured-game-thumb">';
echo '<img src="img/images/featured_game_thumb02.jpg" alt="">';
echo '</div>';
echo '<div class="featured-game-content">';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '<div class="featured-game-content featured-game-overlay-content">';
echo '<div class="featured-game-icon"><img src="img/icon/featured_game_icon.png" alt=""></div>';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-6 grid-item">';
echo '<div class="featured-game-item mb-30">';
echo '<div class="featured-game-thumb">';
echo '<img src="img/images/featured_game_thumb03.jpg" alt="">';
echo '</div>';
echo '<div class="featured-game-content">';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '<div class="featured-game-content featured-game-overlay-content">';
echo '<div class="featured-game-icon"><img src="img/icon/featured_game_icon.png" alt=""></div>';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-6 grid-item">';
echo '<div class="featured-game-item mb-30">';
echo '<div class="featured-game-thumb">';
echo '<img src="img/images/featured_game_thumb04.jpg" alt="">';
echo '</div>';
echo '<div class="featured-game-content">';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '<div class="featured-game-content featured-game-overlay-content">';
echo '<div class="featured-game-icon"><img src="img/icon/featured_game_icon.png" alt=""></div>';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-6 grid-item">';
echo '<div class="featured-game-item mb-30">';
echo '<div class="featured-game-thumb">';
echo '<img src="img/images/featured_game_thumb06.jpg" alt="">';
echo '</div>';
echo '<div class="featured-game-content">';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '<div class="featured-game-content featured-game-overlay-content">';
echo '<div class="featured-game-icon"><img src="img/icon/featured_game_icon.png" alt=""></div>';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-6 grid-item">';
echo '<div class="featured-game-item mb-30">';
echo '<div class="featured-game-thumb">';
echo '<img src="img/images/featured_game_thumb05.jpg" alt="">';
echo '</div>';
echo '<div class="featured-game-content">';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '<div class="featured-game-content featured-game-overlay-content">';
echo '<div class="featured-game-icon"><img src="img/icon/featured_game_icon.png" alt=""></div>';
echo '<h4><a href="game-single2.php">FEATURED <span>GAMES</span></a></h4>';
echo '<div class="featured-game-meta">';
echo '<i class="fas fa-bell"></i>';
echo '<span>PC, Console</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- featured-game-area-end -->';
echo '';
echo '<!-- cta-area -->';
echo '<section class="cta-area cta-bg">';
echo '<div class="container">';
echo '<div class="row align-items-center justify-content-between">';
echo '<div class="col-xl-5 col-lg-6">';
echo '<div class="cta-img">';
echo '<img src="img/images/cta_img.png" alt="">';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<div class="cta-content">';
echo '<div class="cta-icon mb-15">';
echo '<img src="img/icon/cta_icon.png" alt="">';
echo '</div>';
echo '<div class="section-title title-style-three white-title mb-50">';
echo '<h2>BE THE <span>CHAMPION</span></h2>';
echo '<p>Do you have what it takes to be the next champion? Join our esport team now.</p>';
echo '</div>';
echo '<div class="cta-btn">';
echo '<a href="game-overview.php" class="btn btn-style-two">JOIN NOW</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- cta-area-end -->';
echo '';
echo '<!-- shop-area -->';
echo '<section class="shop-area black-bg pt-115 pb-90">';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-xl-6 col-lg-8">';
echo '<div class="section-title title-style-three white-title text-center mb-40">';
echo '<h2>Gaming Products <span>Corner</span></h2>';
echo '<p>Shop the latest Gaming products such as ASUS, MSI, RAZER, ACER and more!</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row product-active">';
echo '<div class="col-xl-3">';
echo '<div class="shop-item">';
echo '<div class="product-thumb">';
echo '<a href="shop.php"><img src="img/product/s_product_img01.jpg" alt=""></a>';
echo '</div>';
echo '<div class="product-content">';
echo '<div class="product-tag"><a href="#">Laptop</a></div>';
echo '<h4><a href="shop.php">Asus ROG Zephyrus G14 22</a></h4>';
echo '<div class="product-meta">';
echo '<div class="product-price">';
echo '<h5>₱86,443.88</h5>';
echo '</div>';
echo '<div class="product-cart-action">';
echo '<a href="#"><i class="fas fa-shopping-basket"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-3">';
echo '<div class="shop-item">';
echo '<div class="product-thumb">';
echo '<a href="shop.php"><img src="img/product/s_product_img02.jpg" alt=""></a>';
echo '</div>';
echo '<div class="product-content">';
echo '<div class="product-tag"><a href="#">Headphones</a></div>';
echo '<h4><a href="shop.php">Logitech G733</a></h4>';
echo '<div class="product-meta">';
echo '<div class="product-price">';
echo '<h5>₱12,300</h5>';
echo '</div>';
echo '<div class="product-cart-action">';
echo '<a href="#"><i class="fas fa-shopping-basket"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-3">';
echo '<div class="shop-item">';
echo '<div class="product-thumb">';
echo '<a href="shop.php"><img src="img/product/s_product_img03.jpg" alt=""></a>';
echo '</div>';
echo '<div class="product-content">';
echo '<div class="product-tag"><a href="#">graphics</a></div>';
echo '<h4><a href="shop.php">GeForce RTX 3060</a></h4>';
echo '<div class="product-meta">';
echo '<div class="product-price">';
echo '<h5>₱36,517.51</h5>';
echo '</div>';
echo '<div class="product-cart-action">';
echo '<a href="#"><i class="fas fa-shopping-basket"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-3">';
echo '<div class="shop-item">';
echo '<div class="product-thumb">';
echo '<a href="shop.php"><img src="img/product/s_product_img04.jpg" alt=""></a>';
echo '</div>';
echo '<div class="product-content">';
echo '<div class="product-tag"><a href="#">Chair</a></div>';
echo '<h4><a href="shop.php">Secret Titan Evo 22</a></h4>';
echo '<div class="product-meta">';
echo '<div class="product-price">';
echo '<h5>₱26,399.5</h5>';
echo '</div>';
echo '<div class="product-cart-action">';
echo '<a href="#"><i class="fas fa-shopping-basket"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-3">';
echo '<div class="shop-item">';
echo '<div class="product-thumb">';
echo '<a href="shop.php"><img src="img/product/s_product_img05.jpg" alt=""></a>';
echo '</div>';
echo '<div class="product-content">';
echo '<div class="product-tag"><a href="#">Monitor</a></div>';
echo '<h4><a href="shop.php">Razer Raptor 27</a></h4>';
echo '<div class="product-meta">';
echo '<div class="product-price">';
echo '<h5>₱41,779.48</h5>';
echo '</div>';
echo '<div class="product-cart-action">';
echo '<a href="#"><i class="fas fa-shopping-basket"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- shop-area-end -->';
echo '';
echo '<!-- blog-area -->';
echo '<section class="blog-area pt-115 pb-120">';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-xl-6 col-lg-8">';
echo '<div class="section-title title-style-three text-center mb-70">';
echo '<h2>Latest News <span>Articles</span></h2>';
echo '<p>Here are the lates news articales related to gaming.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="blog-post blog-style-two mb-50">';
echo '<div class="blog-thumb mb-30">';
echo '<a href="blog.php"><img src="img/blog/s_blog_thumb01.jpg" alt=""></a>';
echo '</div>';
echo '<div class="blog-post-content">';
echo '<h4><a href="blog.php">Finding A PS5 Might Get Easier This Year</a></h4>';
echo '<div class="blog-meta">';
echo '<ul>';
echo '<li><i class="far fa-clock"></i>March 24, 2022</li>';
echo '<li><i class="fas fa-tag"></i><a href="#">Console</a></li>';
echo '</ul>';
echo '</div>';
echo '<p style="text-align: justify">Sony has projected it will sell many millions more PlayStation 5 units in the current fiscal year and this could be a sign that the company [...]</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="blog-post blog-style-two mb-50">';
echo '<div class="blog-thumb mb-30">';
echo '<a href="blog.php"><img src="img/blog/s_blog_thumb02.jpg" alt=""></a>';
echo '</div>';
echo '<div class="blog-post-content">';
echo '<h4><a href="blog.php">Gotham Knights Will Only Be Available On PC and Consoles</a></h4>';
echo '<div class="blog-meta">';
echo '<ul>';
echo '<li><i class="far fa-clock"></i>March 24, 2022</li>';
echo '<li><i class="fas fa-tag"></i><a href="#">Game</a></li>';
echo '</ul>';
echo '</div>';
echo '<p style="text-align: justify">Gotham Knights developer Warner Bros. Montreal has revealed new gameplay footage for its upcoming [...]</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="blog-post blog-style-two mb-50">';
echo '<div class="blog-thumb mb-30">';
echo '<a href="blog.php"><img src="img/blog/s_blog_thumb03.jpg" alt=""></a>';
echo '</div>';
echo '<div class="blog-post-content">';
echo '<h4><a href="blog.php">GameStop now has its own wallet for crypto and NFTs</a></h4>';
echo '<div class="blog-meta">';
echo '<ul>';
echo '<li><i class="far fa-clock"></i>March 25, 2022</li>';
echo '<li><i class="fas fa-tag"></i><a href="#">Crypto</a></li>';
echo '</ul>';
echo '</div>';
echo '<p style="text-align: justify">GameStop has launched a beta for its very own Ethereum wallet that will let users store, send, and receive [...]</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- blog-area-end -->';
echo '';
echo '</main>';
echo '<!-- main-area-end -->';
echo '';
echo '<!-- footer-area -->';
echo '<footer>';
echo '<div class="footer-top footer-bg s-footer-bg">';
echo '<!-- newsletter-area -->';
echo '<div class="newsletter-area s-newsletter-area">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-12">';
echo '<div class="newsletter-wrap">';
echo '<div class="section-title newsletter-title">';
echo '<h2>Our <span>Newsletter</span></h2>';
echo '</div>';
echo '<div class="newsletter-form">';
echo '<form action="#">';
echo '<div class="newsletter-form-grp">';
echo '<i class="far fa-envelope"></i>';
echo '<input type="email" placeholder="Enter your email..">';
echo '</div>';
echo '<button>SUBSCRIBE <i class="fas fa-paper-plane"></i></button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- newsletter-area-end -->';
echo '<div class="container">';
echo '<div class="row justify-content-between">';
echo '<div class="col-xl-3 col-lg-4 col-md-6">';
echo '<div class="footer-widget mb-50">';
echo '<div class="footer-logo mb-35">';
echo '<a href="index.html"><img src="img/logo/logo.png" alt=""></a>';
echo '</div>';
echo '<div class="footer-text">';
echo '<p>Gemas marketplace the relase etras thats sheets continig passag.</p>';
echo '<div class="footer-contact">';
echo '<ul>';
echo '<li><i class="fas fa-map-marker-alt"></i> <span>Address : </span>Bangbangalon, Boac, Marinduque</li>';
echo '<li><i class="fas fa-headphones"></i> <span>Phone : </span>+24 1245 654 235</li>';
echo '<li><i class="fas fa-envelope-open"></i><span>Email : </span>tjtimtiman121901@gmail.com</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-2 col-lg-3 col-sm-6">';
echo '<div class="footer-widget mb-50">';
echo '<div class="fw-title mb-35">';
echo '<h5>Links</h5>';
echo '</div>';
echo '<div class="fw-link">';
echo '<ul>';
echo '<li><a href="home.php">Home</a></li>';
echo '<li><a href="about-us.php">Our Story</a></li>';
echo '<li><a href="game-overview.php">Overview</a></li>';
echo '<li><a href="community.php">Community</a></li>';
echo '<li><a href="shop.php">Store</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-2 col-lg-3 col-sm-6">';
echo '<div class="footer-widget mb-50">';
echo '<div class="fw-title mb-35">';
echo '<h5>Need Help?</h5>';
echo '</div>';
echo '<div class="fw-link">';
echo '<ul>';
echo '<li><a href="#">Terms & Conditions</a></li>';
echo '<li><a href="#">Privacy Policy</a></li>';
echo '<li><a href="#">Refund Policy</a></li>';
echo '<li><a href="#">Affiliate</a></li>';
echo '<li><a href="#">FAQ</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-xl-3 col-lg-4 col-md-6">';
echo '<div class="footer-widget mb-50">';
echo '<div class="fw-title mb-35">';
echo '<h5>Follow us</h5>';
echo '</div>';
echo '<div class="footer-social">';
echo '<ul>';
echo '<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-twitter"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>';
echo '<li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="footer-widget mb-50">';
echo '<div class="fw-title mb-35">';
echo '<h5>Newsletter Sign Up</h5>';
echo '</div>';
echo '<div class="footer-newsletter">';
echo '<form action="#">';
echo '<input type="text" placeholder="Enter your email">';
echo '<button><i class="fas fa-rocket"></i></button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="footer-fire"><img src="img/images/sword_fire.png" alt=""></div>';
echo '<div class="footer-fire footer-fire-right"><img src="img/images/sword_ice.png" alt=""></div>';
echo '</div>';
echo '<div class="copyright-wrap s-copyright-wrap">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 col-md-6">';
echo '<div class="copyright-text">';
echo '<p>Copyright © 2022 <a href="#">Vessel</a> All Rights Reserved.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 col-md-6 d-none d-md-block">';
echo '<div class="payment-method-img text-right">';
echo '<img src="img/images/card_img.png" alt="img">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '<!-- footer-area-end -->';
?>





		<!-- JS here -->
        <script src="js/vendor/jquery-3.4.1.min.js"></script>
        <script src="js/popper.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/isotope.pkgd.min.js"></script>
        <script src="js/slick.min.js"></script>
        <script src="js/jquery.meanmenu.min.js"></script>
        <script src="js/wow.min.js"></script>
        <script src="js/aos.js"></script>
        <script src="js/jquery.lettering.js"></script>
        <script src="js/jquery.textillate.js"></script>
        <script src="js/jquery.odometer.min.js"></script>
        <script src="js/jquery.appear.js"></script>
        <script src="js/owl.carousel.min.js"></script>
        <script src="js/jquery.countdown.min.js"></script>
        <script src="js/jquery.scrollUp.min.js"></script>
        <script src="js/imagesloaded.pkgd.min.js"></script>
        <script src="js/jquery.magnific-popup.min.js"></script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>
